"""remove less fields

Revision ID: 71ed81644c34
Revises: 80426ff0cefc
Create Date: 2023-11-22 19:14:29.819796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71ed81644c34'
down_revision = '80426ff0cefc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_data_id', table_name='user_data')
    op.drop_table('user_data')
    op.drop_index('ix_visited_domains_user_id', table_name='visited_domains')
    op.drop_column('visited_domains', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visited_domains', sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_visited_domains_user_id', 'visited_domains', ['user_id'], unique=False)
    op.create_table('user_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_request_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_data_pkey')
    )
    op.create_index('ix_user_data_id', 'user_data', ['id'], unique=False)
    # ### end Alembic commands ###
