"""init db structure

Revision ID: 80426ff0cefc
Revises: 
Create Date: 2023-11-20 14:48:26.104199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80426ff0cefc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('total_request_count', sa.Integer(), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_id'), 'user_data', ['id'], unique=False)
    op.create_table('visited_domains',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visited_domains', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tracked_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_visited_domains_tracked_at'), 'visited_domains', ['tracked_at'], unique=False)
    op.create_index(op.f('ix_visited_domains_user_id'), 'visited_domains', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visited_domains_user_id'), table_name='visited_domains')
    op.drop_index(op.f('ix_visited_domains_tracked_at'), table_name='visited_domains')
    op.drop_table('visited_domains')
    op.drop_index(op.f('ix_user_data_id'), table_name='user_data')
    op.drop_table('user_data')
    # ### end Alembic commands ###
